BEGIN TRANSACTION;
CREATE TABLE citacao (_id INTEGER PRIMARY KEY, frase TEXT);
INSERT INTO citacao VALUES(1,'A nossa felicidade será naturalmente proporcional em relação à felicidade que fizermos para os outros.');
INSERT INTO citacao VALUES(2,'Os homens semeiam na terra o que colherão na vida espiritual: os frutos da sua coragem ou da sua fraqueza.');
INSERT INTO citacao VALUES(3,'Os espíritos protetores nos ajudam com os seus conselhos, através da voz da consciência, que fazem falar em nosso íntimo - mas como nem sempre lhes damos a necessária importância, oferecem-nos outros mais diretos, servindo-se das pessoas que nos cercam.');
INSERT INTO citacao VALUES(4,'O homem é assim o árbitro constante de sua própria sorte. Ele pode aliviar o seu suplício ou prolongá-lo indefinidamente. Sua felicidade ou sua desgraça dependem da sua vontade de fazer o bem.');
INSERT INTO citacao VALUES(5,'Nascer, morrer, renascer ainda e progredir sempre, tal é a lei.');
INSERT INTO citacao VALUES(6,'Com a inveja e o ciúme, não há calma nem repouso para aquele que está atacado desse mal: os objetos de sua cobiça, de seu ódio, de seu despeito, se levantam diante dele como fantasmas que não lhe dão nenhuma trégua e o perseguem até no sono.');
INSERT INTO citacao VALUES(7,'O verdadeiro homem de bem é aquele que faz a outrem aquilo que queria que os outros lhe fizessem.');
INSERT INTO citacao VALUES(8,'A fé necessita de uma base, e essa base é a perfeita compreensão daquilo em que se deve crer. Para crer, não basta ver, é necessário compreender.');
INSERT INTO citacao VALUES(9,'O progresso da humanidade tem seu princípio na aplicação da lei de justiça, de amor e de caridade.');
INSERT INTO citacao VALUES(10,'Estude a si mesmo, observando que o autoconhecimento traz humildade e sem humildade é impossível ser feliz.');
INSERT INTO citacao VALUES(11,'O sublime da virtude consiste no sacrifício do interesse pessoal para o próximo, sem oculta intenção.');
INSERT INTO citacao VALUES(12,'O egoísmo é a fonte de todos os vícios, como a caridade é a fonte de todas as virtudes. Destruir um e desenvolver o outro, tal deve ser o objetivo de todos os esforços do homem, se quer assegurar sua felicidade neste mundo, tanto quanto no futuro.');
INSERT INTO citacao VALUES(13,'Honrar o pai e a mãe não é somente respeitá-los, mas também assisti-los nas suas necessidades; proporcionar-lhes o repouso na velhice; cercá-los de solicitude, como eles fizeram por nós na infância.');
INSERT INTO citacao VALUES(14,'Os espíritos protetores nos ajudam com os seus conselhos, através da voz da consciência, que fazem falar em nosso íntimo - mas como nem sempre lhes damos a necessária importância, oferecem-nos outros mais diretos, servindo-se das pessoas que nos cercam.');
INSERT INTO citacao VALUES(15,'A pureza de coração é inseparável da simplicidade e da humildade.');
INSERT INTO citacao VALUES(16,'Você receberá, de retorno, tudo o que der aos outros, segundo a lei que nos rege os destinos.');
INSERT INTO citacao VALUES(17,'Deus colocou no coração do homem a regra de toda a verdadeira justiça, pelo desejo de cada um de ver seus direitos respeitados.');
INSERT INTO citacao VALUES(18,'Para crer, não basta ver, é necessário compreender.');
INSERT INTO citacao VALUES(19,'O meio mais eficaz de combater a predominância da natureza corporal, é praticando a abnegação corporal.');
INSERT INTO citacao VALUES(20,'É certo que, no bom sentido, a confiança nas próprias forças torna-nos capazes de realizar coisas materiais que não podemos fazer, quando duvidamos de nós mesmos.');
INSERT INTO citacao VALUES(21,'O homem deve se resignar e suportar os males sem murmurar, se quer progredir.');
INSERT INTO citacao VALUES(22,'Vosso espírito se elevará mais depressa se já progrediu em inteligência.');
INSERT INTO citacao VALUES(23,'No intervalo das encarnações, aprendeis em uma hora o que vos exigiria anos sobre a vossa terra.');
INSERT INTO citacao VALUES(24,'A paixão está no excesso acrescentado à vontade, porque o princípio foi dado ao homem para o bem e as paixões podem levá-lo a grandes coisas, sendo o abuso que delas se faz que causa o mal.');
INSERT INTO citacao VALUES(25,'Com suas paixões, o homem criou para si suplícios voluntários, e a Terra torna-se para ele um verdadeiro inferno.');
INSERT INTO citacao VALUES(26,'Os obstáculos ao cumprimento da lei divina decorrem dos preconceitos sociais e não da lei civil.');
INSERT INTO citacao VALUES(27,'O sábio, para ser feliz, olha abaixo de si e jamais acima, a não ser para elevar sua alma até o infinito.');
INSERT INTO citacao VALUES(28,'Na ausência dos fatos, a dúvida se justifica no homem ponderado.');
INSERT INTO citacao VALUES(29,'Certos pais, é verdade, descuidam de seus deveres, e não são para os filhos o que deviam ser. Mas é a Deus que compete puni-los, e não aos filhos.');
INSERT INTO citacao VALUES(30,'A cada nova existência, o homem tem mais inteligência e pode melhor distinguir o bem e o mal.');
INSERT INTO citacao VALUES(31,'Depende do homem amenizar seus males e ser tão feliz quanto se pode ser sobre a Terra.');
INSERT INTO citacao VALUES(32,'O apego às coisas materiais é um sinal notório de inferioridade, porque quanto mais o homem se prende aos bens do mundo, menos compreende sua destinação.');
INSERT INTO citacao VALUES(33,'A lei natural traça ao homem o limite de suas necessidades, e quando ela a ultrapassa, é punido pelo sofrimento.');
INSERT INTO citacao VALUES(34,'O sinal mais característico da imperfeição do homem, é o seu interesse pessoal.');
INSERT INTO citacao VALUES(35,'A felicidade dos espíritos é sempre proporcional à sua elevação.');
INSERT INTO citacao VALUES(36,'Toda pessoa que serve além do dever, encontrou o caminho para a verdadeira felicidade.');
INSERT INTO citacao VALUES(37,'Há leis naturais e imutáveis, sem dúvida, que Deus não pode anular segundo os caprichos de cada um. Mas daí a acreditar que todas as circunstâncias da vida estejam submetidas à fatalidade, a distância é grande.');
INSERT INTO citacao VALUES(38,'Os bons espíritos simpatizam com os homens de bem, ou suscetíveis de se melhorar. Os espíritos inferiores, com os homens viciosos ou que podem viciar-se. Daí seu apego, resultante da semelhança de sensações.');
INSERT INTO citacao VALUES(39,'Deus colocou no coração do homem a regra de toda a verdadeira justiça, pelo desejo de cada um de ver seus direitos respeitados.');
INSERT INTO citacao VALUES(40,'Os espíritos protetores nos ajudam com os seus conselhos, através da voz da consciência, que fazem falar em nosso íntimo - mas como nem sempre lhes damos a necessária importância, oferecem-nos outros mais diretos, servindo-se das pessoas que nos cercam.');
INSERT INTO citacao VALUES(41,'O egoísmo é a fonte de todos os vícios, como a caridade é a fonte de todas as virtudes. Destruir um e desenvolver o outro, tal deve ser o objetivo de todos os esforços do homem, se quer assegurar sua felicidade neste mundo, tanto quanto no futuro.');
INSERT INTO citacao VALUES(42,'O sublime da virtude consiste no sacrifício do interesse pessoal para o próximo, sem oculta intenção.');
INSERT INTO citacao VALUES(43,'O progresso da humanidade tem seu princípio na aplicação da lei de justiça, de amor e de caridade.');
INSERT INTO citacao VALUES(44,'A fé necessita de uma base, e essa base é a perfeita compreensão daquilo em que se deve crer. Para crer, não basta ver, é necessário compreender.');
INSERT INTO citacao VALUES(45,'O verdadeiro homem de bem é aquele que faz a outrem aquilo que queria que os outros lhe fizessem.');
COMMIT;
